title: Hafid Miftahurrosyad
profile_img: /assets/img/profile.png
icon_img: /assets/img/favicon.png

name: "Haviedz Miftah"
job: "Teacher - Videographer - Desainer - Web Developer"

# phone_number: dm instagram aja ya
# address: Ngawi, Jawa Timur
email: haviedzmiftah@gmail.com
linkedin_username: haviedzmiftah
github_username: haviedzmiftah
instagram_username: haviedzmiftah
twitter_username: haviedzmiftah
facebook_username: havied2
youtube_username: haviedzmiftah
blog_url: https://haviedzmiftah.github.io/blog

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
