# Site settings
title: Haviedz Miftah
email: haviedzmiftah@gmail.com
url: https://haviedzmiftah.github.io
description: ""
keywords: "haviedz miftah"
skills: "Web Developer - Video Editor - Desainer"
meta_author: LastName FirstName

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: E5E4E2
  primary-rgb: 61, 61, 61
  secondary: 28282b
  secondary-dark: 242424

# Footer settings
footer:
  copyright: Haviedz Miftah
  # location: Ngawi
  social: Media Sosial
  # credits: Credits

# Social networks usernames
social:
  - title: twitter
    url: http://twitter.com/HaviedzMiftah
  - title: facebook
    url: http://facebook.com/havied2
  - title: instagram
    url: http://instagram.com/haviedzmiftah
  - title: youtube
    url: https://www.youtube.com/@haviedzmiftah
  - title: github
    url: http://github.com/haviedzmiftah

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: "/blog/:title/"
